export const ScreenConstants = {
    LOGIN: 'Login',
    FORGOT_PASSWORD: 'ForgotPassword',
    OTP_VERIFICATION: 'OtpVerification',
    SIGN_UP: 'SignUp',
    RESET_PASSWORD: 'ResetPassword',
    BOTTOM_TAB_NAVIGATOR: 'BottomTabNavigator',
    MY_PLANTS: 'MyPlants',
    PARCELS: 'Parcels',
    MAP_SCREEN: 'MapScreen',
    SOIL_MAP_DETAILS: 'SoilMapDetails',
    PARCEL_ALERTS: 'ParcelAlerts',
    NOTIFICATIONS: 'Notifications',
    NOTIFICATION_SETTINGS: 'NotificationSettings',
    PROFILE: 'Profile',
    PARCEL_DETAILS: 'ParcelDetails',
    PLANTING_GUIDANCE: 'PlantingGuidance',
    ABOUT: 'About',
    ASSIGN_TO_PARCEL: 'AssignToParcel',
    PLANTING_TIPS: 'PlantingTips',
    REMINDERS: 'Reminders',
    AI_CHAT: 'AiChat',
    DOWNLOADS: 'Downloads',
    SUBSCRIPTION_PLANS: 'SubscriptionPlans',
    
}