export const StringConstants = {
   ACCESS_TOKEN: 'AccessToken',
   USER_CREDENTIALS: 'userCredentials',

   LOGIN: 'Login',
   RIGHT_TREE_RIGHT_PLACE: 'Right Tree, Right Place',
   DESCRIPTION_LOGIN: '. Powered by soil data and GPS for smarter planting. ',
   EMAIL: 'Email',
   PASSWORD: 'Password',
   NEW_PASSWORD: 'New Password',
   CONFIRM_PASSWORD: 'Confirm Password',
   REMEMBER_ME: 'Remember Me',
   FORGOT_PASSWORD: 'Forgot Password?',
   DONT_HAVE_ACCOUNT: "Don't have an account Yet? ",
   SIGN_UP: 'Sign Up',
   FORGOT_PASSWORD2: 'Forgot Password',
   CONTINUE: 'Continue',
   OR_CONTINUE_WITH: 'OR Continue with',
   OTP_VERIFICATION: 'OTP Verification',
   CONFIRM: 'Confirm',
   RESEND_OTP: 'Resend OTP',
   DID_NOT_GET_OTP_YET: 'Didn’t Get the OTP Yet? ',
   CREATE_ACCOUNT: 'Create Account',
   FULL_NAME: 'Full Name',
   FIRST_NAME: 'First Name',
   LAST_NAME: 'Last Name',
   CREATE_PASSWORD: 'Create Password',

   //Home
   MY_PARCELS: 'My Parcels',
   MOISTURE: 'Moisture',
   ACIDITY: 'Acidity',
   FERTILITY: 'Fertility',
   MINERALS: 'Minerals',
   MY_PLANTS: 'My Plants',
   NOTIFICATIONS: 'Notifications',
   PARCELS: 'Parcels',
   RECOMMENDATION_LINE: 'Our saved locations and soil-based tree recommendations.',
   ADD_NEW: ' Add New',
   AI_TOOL: 'AI Tool',
   PROFILE: 'Profile',
   FREE_PLAN: 'Free Plan',
   NOT_SUBSCRIBE: 'Not Subscribe',
   UPGRADE_PLAN: 'Upgrade Plan',
   QUICK_ACTIONS: 'Quick Actions',
   PLAN_AND_SUBSCRPTION: 'Plan & Subscription',
   NOTIFICATION_AND_REMINDERS: 'Notification & Reminders',
   OFFLINE_DOWNLOADS: 'Offline Downloads',
   LOGOUT: 'Logout',
   ENTER_YOUR_LOCATION: 'Enter Your Location',
   PREFERRED: 'Preferred',
   LIMITATIONS: 'Limitations:',
   MODERATE_EROSION: 'Moderate erosion potential on slopes.\nCompaction risk with heavy machinery.',
   GUIDANCE: 'Guidance',
   PARCEL_DETAIL: 'Parcel Detail',
   PARCEL_ALERTS:'Parcel Alerts',
   NOTIFICATION: 'Notification',
   LAND_USE_HISTORY: 'Land Use History',
   TIME_RANGE: 'Time Range',
   PLANTATION_HISTORY: 'Plantation History',
   PLANTING_GUIDANCE: 'Planting Guidance',
   ABOUT: 'About',
   TREE_APPROPRIATE_LANGUAGE: 'Tree-appropriate language:',
   PHOTOS: 'Photos',
   LEAF: 'Leaf',
   BARK: 'Bark',
   FRUIT: 'Fruit',
   TREE: 'Tree',
   BEHAVIOUR: 'Behaviour',
   FLOWER: 'Flower',
   DISEASES: 'Diseases',
   FALL: 'Fall',
   MAINTENANCE_TIPS: 'Maintenance Tips',
   TIP1: 'Deep water once a week during dry periods.',
   TIP2: 'Protect young trunks with tree guards to prevent',
   TIP3: 'Watch for signs of oak wilt, root rot, scale, or caterpillars.',
   TIP4: 'Avoid topping or heavy trimming—it stresses the tree.',
   PLANTING_DATE: 'Planting date',
   ADD_TREE: 'Add Tree',
   YOU_MAY_ADD_MULTIPLE_TREE: 'You may add Multiple or single Tree',
   PLANTING_TIPS: 'Planting Tips',
   REMINDERS: 'Reminders',
   AI_CHAT: 'AI Chat',
   SEND_A_MESSAGE: 'Send a message',
   DOWNLOADS: 'Downloads',
   SUBSCRIPTION_PLANS: 'Subscription Plans',



}